title: "DriVonacci"
description: "戦略実装・業務改善コンサルティング"

url: "https://drivonacci.com"
baseurl: ""

name: "植木 真人"
role: "Business Process Optimizer"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

header_pages:
  - about.md
  - services.md
  - portfolio.md
  - contact.md

company:
  name: "DriVonacci"
  tagline: "戦略実装・業務改善コンサルティング"
  
achievements:
  cost_reduction: "年間400万円"
  productivity: "246%向上"
  automation_hours: "1,356時間/年"

